### PR TITLE
Add support for GHC 9.0

### PR DESCRIPTION
**Pull request by michivi**
Add support for GHC 9.0.2.

### CODE REVIEW

**Comment by ocharles** [comment]
Thanks, looks good! Would you be interested in helping maintain this library? I don't believe it has an active maintainer.

**Comment by michivi** [comment]
Thanks, but I'm afraid I won't have enough time for that. Hopefully, someone else will have time to carry the torch!

**Comment by ChickenProp** [comment]
@ocharles My company (https://github.com/proda-ai/) would be interested in helping maintain.

**Comment by ocharles** [comment]
@ChickenProp Wonderful! I'll add you as a maintainer here. What's your Hackage handle?

**Comment by ocharles** [comment]
@chessai @treeowl I don't have right to add contributors - could you add @ChickenProp ?

**Comment by treeowl** [comment]
@ocharles , does @ChickenProp have a history of contributions here?

**Comment by ocharles** [comment]
No, but I trust them to do good.

Edit: but @ChickenProp does have a history of contribution in other projects that I've worked on.

**Comment by treeowl** [comment]
Okay, invited to the organization. Will invite to the repo once accepted, and will add on Hackage once I have the username for that.

**Comment by ocharles** [comment]
Awesome, thanks! Happy hacking, @ChickenProp, and thank you for your help!

**Comment by ChickenProp** [comment]
Thank you both! I've accepted the org invite.

Ah, embarrassingly we don't actually have a hackage username yet, this is us as an org and also me personally dipping our toe into maintaining things on hackage. I'm not sure exactly how it works, in particular if we're able to have an account for the org or whether I should just set one up for myself. But I'll look into that and let you know the username probably tomorrow.

**Comment by treeowl** [comment]
You should now have write access to this repo. I guess there's no separate invitation? Thanks!

**Comment by ChickenProp** [comment]
Okay, my hackage username is PhilHazelden.

**Comment by treeowl** [comment]
Ha ha, I just realized I'm not the one with Hackage access to this bit. Who the heck has it?

**Comment by ocharles** [comment]
I do, I've added you @ChickenProp.

**Comment by ChickenProp** [comment]
Thank you! I just added a revision with GHC 9 support.

**Pull request merged**
